name: daily RKI SurvStat scraping and processing

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9-14 * * *"

jobs:
  rki_survstat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update apt
        run: sudo apt-get update
      - name: install gnuplot
        run: sudo apt-get install -y fonts-linuxlibertine gnuplot
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas requests beautifulsoup4 webdriver-manager selenium
      - name: scrape RKI SurvStat data
        run: |
          cd scraper/ 
          env python3 ./rki_survstat_scraper.py 
          env python3 ./rki_survstat_scraper_genders.py 
          env python3 ./rki_survstat_district_scraper.py 
          env python3 ./rki_survstat_processing.py 
          env python3 ./rki_survstat_processing_districts.py 
          cd ../
      - name: update graphs
        run: |
          cd gnuplot/ 
          ./update_graphs.sh
          cd ../
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./data/*.csv
          git add ./data/RKI_SurvStat_by_date/*.csv
          git add ./data/RKI_SurvStat_by_date_*/*.csv
          git add ./data/RKI_SurvStat_by_date_and_district/*.csv
          git add ./data/RKI_SurvStat_by_date_and_district_*/*.csv
          git add ./plots_de/*.png
          git add ./plots_en/*.png
          git diff-index --quiet HEAD || git commit -m "daily RKI SurvStat scraping and processing"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
